site_name: PROOF Documentation

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true

theme:
  name: mkdocs
  user_color_mode_toggle: true
  features:
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search
    - search.suggest
    - search.highlight

  #  - navigation.sections
  #include_sidebar: true



nav:
  - Installation: Installation/installation.md
  - Workflow:
    - Overview: Workflow/proof-workflows.md
    - Creating Workflows: Workflow/creating-workflows.md
    - Running Workflows: Workflow/running-workflows.md
    - Monitoring Workflows: Workflow/monitoring-workflows.md
  - Blocks:
    - Overview: Block/overview.md
    - Using Blocks: Block/using-proof-blocks.md
    - Creating new Blocks: Block/creating-new-templates.md
      # - Changing Blocks: Block/using-proof-blocks.md
  #- Program: Program/proof-programs.md
    #- Overview: Program/proof-programs.md  
  - FAQ: faq.md
  - About: About/about.md

copyright: (c) 2025 Karlsruhe Institute of Technology (KIT), Institute for Automation and Applied Informatics (IAI)
