site_name: PROOF Documentation

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true

theme:
  name: mkdocs
  user_color_mode_toggle: true
  features:
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search
    - search.suggest
    - search.highlight

  #  - navigation.sections
  #include_sidebar: true



nav:
  - Getting Started: GettingStarted/getting-started.md
  - Workflows:
    - Workflow Structure: Workflow/proof-workflows.md
    - Creating Workflows: UI/creating-workflows.md
    - Monitoring Workflows: Workflow/monitoring-workflows.md
  - Blocks:
    - Introduction: Block/overview.md
    - Using Blocks: UI/using-proof-blocks.md
    - Creating new Blocks: Block/creating-new-templates.md
    #- Changing Blocks: Block/using-proof-blocks.md
  #- Program: Program/proof-programs.md
    #- Overview: Program/proof-programs.md 
  - UI:
    - Creating Workflows: UI/creating-workflows.md
    - Monitoring: Workflow/monitoring-workflows.md
    - Configuration: UI/configs.md
  - FAQ: faq.md
  - About: About/about.md

copyright: (c) 2025 Karlsruhe Institute of Technology (KIT), Institute for Automation and Applied Informatics (IAI)
